# Generated by Django 3.1.3 on 2020-11-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201116_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='authors',
            new_name='participants',
        ),
    ]
